<?php

/**
 * Short description.
 * @see http://doc.example.com/
 *
 * @see SomeClass::someMethod()
 * @Route("/{id}/", name="test")
 * @Security()
 * @param string $a
 *
 *
 * @param string $b
 * @return bool
 * @throws \Exception
 */

/**
 * Short description.
 * @var string
 */

/**
 * Short description
 * on several lines.
 *
 *
 *
 * @param string $a Some long
 *                  description
 * @param string $b Another long
 *                  description
 * @return bool Long
 *              description
 *
 * @throws \Exception
 */

/**
 * @var string $a
 */

/**
 * @param string $a
 *
 * some string
 *
 * @return bool
 */

/**
 * Short description.
 *
 * Long description.
 */

/**
 * Short description.
 *
 * Long description.
 *
 * @param string $a
 */
