<?php

class Test
{
    /**
     * Short description.
     */

    /**
     *
     */

    /**
     */

    /** */

    /**
     *
     * Short description.
     */

    /**
     * Short description.
     *
     */

    /**   Short description.
     */

    /** Short description. */

    /**
     * Short description.   */

    private $a; /**  */

    private $b; /**  */ private $c;

    /**  */ private $d;

    private $e; /**
                 *
                 */ private $f;
}
