<?php

/**
 * Short description.
 * @see http://doc.example.com/
 *
 * @see SomeClass::someMethod()
 * @Route("/{id}/", name="test")
 * @Security()
 * @param string $a
 *
 *
 * @param string $b
 * @return bool
 * @throws \Exception
 */

/**
 * Short description.
 * @var string
 */

/**
 * Short description
 * on several lines.
 *
 *
 *
 * @param string $a Some long
 *                  description
 * @param string $b Another long
 *                  description
 * @return bool Long
 *              description
 *
 * @throws \Exception
 */

/**
 * @var string $a
 */

/**
 * @param string $a
 *
 * some string
 *
 * @return bool
 */

/**
 * Short description.
 *
 * Long description.
 */

/**
 * Short description.
 *
 * Long description.
 *
 * @param string $a
 */

/**
 * @Route("/{id}/")
 * @param
 */

/**
 * @param string $a
 *
 * @return string
 *
 * @param string $b
 */

/**
 * An override of Twig's Lexer to add whitespace and new line detection.
 *
 * Since the regex are using bytes as position, mb_ methods are voluntary not used.
 * phpcs:disable SymfonyCustom.PHP.EncourageMultiBytes
 *
 * @phpstan-type TokenizerOptions = array{
 *     tag_comment: array{string, string},
 *     tag_block: array{string, string},
 *     tag_variable: array{string, string},
 *     whitespace_trim: string,
 *     whitespace_line_trim: string,
 *     interpolation: array{string, string},
 * }
 * @phpstan-type Regex = array{
 *     lex_block: string,
 *     lex_comment: string,
 *     lex_variable: string,
 *     operator: string,
 *     lex_tokens_start: string,
 *     interpolation_start: string,
 *     interpolation_end: string,
 *     lex_block: string,
 * }
 */
